### ISSUE TITLE
Configurable file location

### ISSUE THREAD

**Issue by bradmont** [jffrymrtn/writeily-pro#102]
An option to change writeily's default files directory would be helpful on devices where it's possible to do so, especially to improve interoperability with other installed apps (eg, I'm using syncthing to sync my notes, but I would rather have them stored in the same place as my other synced folders).

**Comment by plafue** [comment]
This has been implemented in #89. I also use syncthing to sync my notes. The current released version does not contain this functionality, though.

**Comment by bradmont** [comment]
Oops! I did a quick look in the issues, but didn't see it. Closing.
