### ISSUE TITLE
Add .md as format of files

### ISSUE THREAD

**Issue by kud** [jffrymrtn/writeily-pro#109]
Could be great to add .md at the end of the filename. I synchronise my writeily folder with my computer, and without .md, it doesn't recognise easily what app it should start to read/edit it.

**Comment by plafue** [comment]
This would help me as well. @jffrymrtn what do you think? We could make it the default for new notes

**Comment by jffrymrtn** [comment]
Sounds good to me. I just looked at our saveNote function in NotesFragment and realized there's no file extension at all... must have overlooked this in version 1.0. 

Not everyone uses Writeily for Markdown (and don't know what .md is) so I guess we can add a .md to the filenames, but just don't show the extension in the ListView? I think it'll just be as easy as substring until the last 3 chars (.md).

**Comment by kud** [comment]
For the moment, I added in my titles ".md" to make it work

Yes, add it in the filename but not in the view. For sure.
