### ISSUE TITLE
Ensure text wraps to fit device width (no horizontal scrolling)

### ISSUE THREAD

**Issue by kud** [jffrymrtn/writeily-pro#113]
I don't know about your devices but on my Galaxy Nexus, the horizontal scroll isn't really cool/smooth. It's like it's done character by character; quite boring.

Plus, we could have maybe a "wrap text" feature which removes the horizontal scroll.

**Comment by plafue** [comment]
Do you mean scrolling within the editor or in the preview? Or when switching from a note to the notes list?

I do experience some laggy behaviour myself when switching back to the notes list.

In any case we use standard android controls, so I'm not really sure how deep we would have to go to improve their performance. Surely we can improve on the way we use them , though.

**Comment by kud** [comment]
When you're in the editor.

Yes, the scroll is done character by character, seems really weird as feeling.

**Comment by jffrymrtn** [comment]
Actually, the app shouldn't even be horizontally scrolling. I'm guessing horizontal scrolling happens for you when you import a file right @kud ? Not when you create one in Writeily itself?

I intended the app to just wrap the files into the screen width (and therfore only vertically scroll), but I encountered this bug a short while ago and thought I had fixed it. Guess it came back =s

**Comment by kud** [comment]
Nope, it always does that. Even when I create a new file via writeily. :/

**Comment by plafue** [comment]
Oh it's the syntax highlighting what breaks the linewrapping! :disappointed: I'm looking into it

**Comment by plafue** [comment]
As a workaround disable syntax highlighting in the settings

**Comment by kud** [comment]
Indeed, thanks ;)
