### ISSUE TITLE
Back button when listing files when you're inside a folder should go back to root

### ISSUE THREAD

**Issue by kud** [jffrymrtn/writeily-pro#116]
Imagine you're in the root. You go inside a folder. You have a button "Back to previous folder". The "back" button from Android should go back to the root of the app, not quiting it.

**Comment by jffrymrtn** [comment]
I think it's already been done by @plafue :)

**Comment by plafue** [comment]
Soooo much cool stuff coming up in the next update... stay tuned! ;)

**Comment by kud** [comment]
I can't wait. ;) Thank you. :)
