### ISSUE TITLE
Adding Korean translation

### ISSUE THREAD

**Issue by halcyonera** [jffrymrtn/writeily-pro#118]
<resources>
    <string name="action_settings">설정</string>
    <string name="open_drawer">서랍 열기</string>
    <string name="close_drawer">서랍 닫기</string>
    <string name="notes">노트</string>
    <string name="archive">보관</string>
    <string name="new_note">새 노트</string>
    <string name="theme_light">밝은 테마</string>
    <string name="theme_dark">어두운 테마</string>
    <string name="delete">삭제</string>
    <string name="rename">이름 바꾸기</string>
    <string name="star">별표</string>
    <string name="starred">별표 추가됨</string>
    <string name="restore">되돌리기</string>
    <string name="wr_import">불러오기</string>
    <string name="unstar">별표 지우기</string>
    <string name="confirm_delete">삭제 확인</string>
    <string name="confirm_overwrite">파일이 이미 있습니다. 덮어쓸까요?</string>
    <string name="enter_new_name">새 이름 입력</string>
    <string name="incorrect_pin_text">잘못된 비밀번호</string>
    <string name="title">제목</string>
    <string name="untitled">제목없음</string>
    <string name="empty_directory">이 폴더는 비어있습니다</string>
    <string name="navigate_up_folder">이전 폴더로 가기</string>
    <string name="folder_name_hint">폴더의 이름을 입력하세요</string>
    <string name="new_name_hint">새 이름을 입력하세요</string>
    <string name="create_folder">폴더 만들기</string>
    <string name="move">이동</string>

    <string name="import_from_device">기기에서 가져오기</string>
    <string name="select_folder_move">폴더 선택</string>
    <string name="select_root_folder">폴더 선택</string>

    <string name="empty_notes_list_hint">새 노트를 만들 때,\n여기에 나타나게 됩니다</string>
    <string name="empty_archives_hint">노트를 보관하게 될 때, \n여기에 나타나게 됩니다</string>
    <string name="empty_starred_hint">노트에 별표를 새길 때,\n여기에 나타나게 됩니다</string>
    <string name="search_hint">노트 검색</string>
    <string name="share_string">&#8230; 공유</string>
    <string name="share">공유</string>
    <string name="search">검색</string>
    <string name="preview">미리보기</string>
    <string name="edit">편집</string>
    <string name="app_settings">앱 설정</string>
    <string name="editor_settings">편집기 설정</string>
    <string name="social">소셜</string>
    <string name="meta">메타</string>
    <string name="directories">폴더</string>
    <string name="files">파일</string>

    <string name="email_header">Writeily에 대한 피드백 제공</string>

    
    <string name="pref_remember_directory">시작할 때 마지막 폴더 위치 기억</string>
    <string name="pref_font_choice">편집기 글꼴 선택</string>
    <string name="pref_theme">테마</string>
    <string name="pref_rate_writeily">Google Play에 Writeily 평점 올리기</string>
    <string name="pref_donate_writeily">기부</string>
    <string name="pref_preview_first">노트 열 때 먼저 미리보기</string>
    <string name="translators_title">번역 제공</string>
    <string name="pref_about_dialog_title">Writeily에 대해서</string>
    <string name="pref_attribution_dialog_title">속성</string>
    <string name="pref_twitter">Twitter에서 Writeily 팔로우</string>
    <string name="pref_email">이메일 지원</string>
    <string name="share_text">평문 텍스트</string>
    <string name="share_image">이미지</string>
    <string name="share_as">&#8230; 공유</string>
    <string name="pref_font_size">글자 크기</string>
    <string name="pref_pin">비밀번호 잠금</string>
    <string name="pref_show_markdown_shortcuts">마크다운 바로가기 바 표시</string>
    <string name="pref_highlighting_activated">마크다운 문법 강조</string>
    <string name="pref_highlighting_delay">강조된 부분을 새로고침할 때 약간 지연시키기</string>
    <string name="pref_highlighting_delay_summary">높을 수록 배터리가 절약됩니다</string>
    <string name="pref_smart_shortcuts">스마트 괄호 바로가기</string>
    <string name="pref_smart_shortcuts_summary">텍스트가 선택됐을 때, {}, [] 그리고 () 가 선택 영역을 감싸게 됨</string>
    <string name="pin_title">비밀번호 입력</string>
    <string name="pin_go">가기</string>

    
    <string name="font_size_normal">보통</string>
    <string name="font_size_large">큼</string>
    <string name="font_size_small">작음</string>

    
    <string name="last_modified">마지막 변경: %s</string>
    <string name="number_of_files">파일 갯수: %d</string>
    <string name="move_here">여기로 이동</string>
    <string name="select_this_folder">이 폴더 선택</string>
    <string name="select">선택</string>
    <string name="no_selected_file">파일 선택되지 않음</string>
    <string name="current_folder">현재 폴더:</string>
    <string name="create">만들기</string>
    <string name="select_elements">항목 선택</string>
    <string name="one_item_selected">하나의 항목 선택됨</string>
    <string name="more_items_selected">%d 개의 항목 선택됨</string>

    
    <string name="about_version_title">버전</string>
    <string name="about_source_title">Writeily는 GitHub에 공개되어 있습니다</string>
    <string name="about_developer_section">제작자</string>
    <string name="about_contributors_section">기여자</string>
    <string name="about_libraries_section">라이브러리</string>
    <string name="about_translators_section">번역 제공자</string>
    <string name="about_german">German</string>
    <string name="about_polish">Polish</string>
    <string name="about_spanish">Spanish</string>
    <string name="about_french">French</string>
    <string name="about_chinese_simplified">Chinese (Simplified)</string>
    <string name="about_italian">Italian</string>
    <string name="tap_website">웹사이트 방문</string>
    <string name="tap_github">Github 프로필</string>
    <string name="rename_error_target_already_exists">파일/폴더가 이미 존재합니다</string>
    <string name="rename_success">이름 바꾸기 성공</string>
    <string name="rename_fail">이름 바꾸기 실패</string>

    </resources>

**Comment by jffrymrtn** [comment]
Will add. Kahmsahmnida :)

**Comment by halcyonera** [comment]
You're welcome, and thanks!
