### ISSUE TITLE
[gh-pages] Remove redundant text from landing page

### ISSUE THREAD

**Issue by deavmi** [jffrymrtn/writeily-pro#127]
This text is redundant (and not aesthetically appealing), as we already have an (aestheticaaly appealing) button for the Google Play download.

![](http://i.imgur.com/ZFuVFU2.png)

**Comment by plafue** [comment]
Thanks for the heads up! I thought I removed it!

**Comment by deavmi** [comment]
@plafue Pleasure :smile:

**Comment by deavmi** [comment]
@plafue Maybe making the bottom text anything but Times New Roman will help. **COMIS ANS**, jk, the font the whole site uses would be nice.

**Comment by plafue** [comment]
Lol, no way! That link's gotta go!

**Comment by deavmi** [comment]
@plafue The other links, the "App by.." and "Follow me"

**Comment by plafue** [comment]
I'll leave the font changes to @jffrymrtn, as he is the look'n'feel master :) I will remove the redundant google play link right away, though, as i know he'll agree :)

**Comment by jffrymrtn** [comment]
@plafue doing it right now :). Took care of the links too. Thanks you two!

**Comment by deavmi** [comment]
No, Thank yous!

**Comment by plafue** [comment]
Oh, race condition! :D

**Comment by jffrymrtn** [comment]
:horse_racing: :scream: commit commit commit!

**Comment by plafue** [comment]
QUICK!! GO GO GO!

**Comment by jffrymrtn** [comment]
Let me know if the font still messes up (shouldnt be times new!).

Someday, I'll actually design the site to use material design... someday :sweat_smile:

**Comment by plafue** [comment]
Cool! I like the white buttons :+1:

**Comment by deavmi** [comment]
@plafue  @jffrymrtn Awesome. Thanks :smile:
