### ISSUE TITLE
Configurable home directory

### ISSUE THREAD

**Issue by jffrymrtn** [jffrymrtn/writeily-pro#26]

**Comment by patcon** [comment]
:+1:

although since bittorrent sync can use arbitrary directories, I recreated it's shared directory at `/sdcard/emulated/0/writeily` and it seems to be syncing fine between my devices. (ie. issue not a blocker for me at least)

**Comment by jffrymrtn** [comment]
@patcon that's really good to know, actually. Does bittorrent sync require root?

**Comment by patcon** [comment]
Nope! Only sdcard access was requested, specifically these perms (from the [Google Play app page](https://play.google.com/store/apps/details?id=com.bittorrent.sync&hl=en)):

> ## Photos/Media/Files
> * modify or delete the contents of your USB storage
> * test access to protected storage

**Comment by fxshpac** [comment]
Just found this great app and wanted to add my vote for supporting configurable home directory :)

**Comment by patcon** [comment]
psssst... throw money at him if you like it and you're able to :)
https://play.google.com/store/apps/details?id=me.writeily.donate

**Comment by jffrymrtn** [comment]
Thanks guys :) my phone broke last week so I haven't been able to do much, but I should be able to get back to it later today.

**Comment by plafue** [comment]
I may give this a shot during the next days. I use syncthing for synching some GTD stuff, and would be cool to keep everything together in the same directory (using syncthing on the writeily folder itself is not a problem, though, so no show stopper here either).

**Comment by jffrymrtn** [comment]
@plafue sure thing! I was going to approach this too, but if you would like to go ahead and code it up, I would encourage it :). It should be quite trivial. I think, the most "tedious" part would be the UI, for which you should be able to use the same directory chooser I use in "Import from Device" or "Move to Folder"

**Comment by jffrymrtn** [comment]
Finished by plafue
