### ISSUE TITLE
Quick Preview

### ISSUE THREAD

**Issue by jffrymrtn** [jffrymrtn/writeily-pro#32]

**Comment by patcon** [comment]
Isn't this available already?

**Comment by jffrymrtn** [comment]
@patcon this will add quick access straight from the notes list (instead of Open Note -> Preview)

**Comment by davydsantos** [comment]
Onde suggestion would be to add a property in the settings to choose if the default openning mode is preview or edit and the "eye" button would work only as a toggle. What do you think? I could try to help with this code ...

**Comment by jffrymrtn** [comment]
Instead of making it a setting, I think I'll have quick preview buttons on
the list view somewhere... Somehow...

The only thing holding me back is the UI. I'll need to mock something up
that doesn't look ugly :s

**Comment by patcon** [comment]
+1 @davydsantos

**Comment by jffrymrtn** [comment]
@davydsantos @patcon after some deliberation, actually starting to lean towards a setting to keep the UI clean and uncluttered!
