### ISSUE TITLE
[bug] Importing a directory tried to import as file

### ISSUE THREAD

**Issue by patcon** [jffrymrtn/writeily-pro#37]
When I choose "Import from device" and choose a directory (assuming it would import the whole directory into writeily), the app seemed to import it as a blank file. I didn't experiment to find out whether saving that file would have overridden the directory with a file of the same name, or whether it would have thrown an error (the directory was important).

**Comment by jffrymrtn** [comment]
@patcon nice catch! I'm preparing 1.1 now, so a fix to this will be in it

**Comment by patcon** [comment]
Shit. You're good.
