### ISSUE TITLE
Use an file chooser/manager library?

### ISSUE THREAD

**Issue by patcon** [jffrymrtn/writeily-pro#38]
Sorry, I know you mentioned somewhere that a big chunk of your work was implementing essentially a new file manager, and I don't want to trivialize that! If it's a bad idea, perhaps you could clarify the rationale. Was just thinking that it might make app upkeep that much easier if a big chunk of the project were maintained elsewhere :)

There are a few out there, but this seems to be the current champion:
https://github.com/iPaulPro/aFileChooser

**Comment by jffrymrtn** [comment]
Thanks for the suggestion! I might just keep what I built now since I've already tested it a lot. If I find something terribly wrong with mine that's worth ditching this is where I'll go though.

**Comment by patcon** [comment]
:+1:
