### ISSUE TITLE
Use semver for tags?

### ISSUE THREAD

**Issue by patcon** [jffrymrtn/writeily-pro#41]
As I was setting up fdroid, I noticed that you're using non-standard versioning: `v1.0` => `1.01`

How would you feel about using straight-up semantic versioning?
http://semver.org/

So according to semver, in an ideal world, we would have gone from `v1.0.0` to `v1.0.1` (assuming that last one was a bugfix and not new features, which would have been `v1.1.0`)

Regardless, the last version bump that happened probably would confuse build systems, as adding a zero like that doesn't mean to them what it might mean to us :)

**Comment by jffrymrtn** [comment]
Alright cool, I'll keep this in mind for 1.1 (aka 1.1.0?)

**Comment by patcon** [comment]
> (aka 1.1.0?)

Yep :) :+1:

**Comment by jffrymrtn** [comment]
@patcon just updated the branch with the new v1.1.0 tag. Let me know if I did anything wrong! Also, the new update is out on the Play Store now (might take an hour to show up) :)

**Comment by patcon** [comment]
Will do! Thanks for everything Jeff!

**Comment by patcon** [comment]
Oh hey, and yeah, either `1.1.0` or `v1.1.0` are up to spec, and any build systems that I've seen accommodate both.
