### ISSUE TITLE
Distinguish between file and folder better

### ISSUE THREAD

**Issue by jffrymrtn** [jffrymrtn/writeily-pro#46]

**Comment by jffrymrtn** [comment]
Update with options:

1. Separate folders and files with ListView headers ("Folders", "Files") like Google Drive
2. Add arrows to the right of folder items to indicate it is hierarchical
3. Change colours of _something_ (icon, background colour, text?) for folders

The main goal: Keep the minimalist look without making the UI too noisy since adding these new elements might do so.

Tagging @Minty123 from #59

**Comment by jffrymrtn** [comment]
I'll be working on this one today, very leaning towards #1, but very open to ideas! If you have other ideas @Minty123, I'd be happy to try them out too! The circled icons was a step in the right direction, though I felt it conflicted with the FAB (and made itself look like a clickable button).

**Comment by Minty123** [comment]
It might help to take a look how various file managers handle this. As of now, I'm in favor of the headers.

**Comment by plafue** [comment]
While working on this i noticed that one has no idea about his position in the hierarchy. Think breadcrumbs. I will implement the labels in a non intrusive fashion, but we should think about some breadcrumbs-like indicator.

**Comment by jffrymrtn** [comment]
I agree. I'd been thinking about this but haven't quite thought out the design. If you want to add it, I can always tweak the design afterwards. It is up to you :)
