### ISSUE TITLE
[Suggestion] Icon change?

### ISSUE THREAD

**Issue by Minty123** [jffrymrtn/writeily-pro#48]
Hey there!

After trying out your app for quite some hours now, I must say that I simply love it!

I just have a suggestion to make about the icon. As the whole app follows the material guidelines pretty close, I thought the icon could be a bit more "material-ish" as well.

Tell me, what you think. :-)

[Edit: I know that the edges of the pencil could be sharper. I would do that later if you like the general idea.]

![writeily_pro_icon](https://cloud.githubusercontent.com/assets/6775975/5820687/f9c243da-a0c6-11e4-856c-e556d76816e4.png)

**Comment by jffrymrtn** [comment]
The white on green is actually a very nice idea! I'll modify the design
files I have to fit the same aesthetic. Although I was pretty happy about
the first icon, a lot of people have said it could be better. This is one
of the better ways to flatten it even more

**Comment by jffrymrtn** [comment]
@Minty123 The new icon in the next update will now reflect this concept, with a few tweaks to how the pen itself looks. I'll add you as a contributor under Attributions for the icon as well :)

**Comment by Minty123** [comment]
@jffrymrtn Awesome, thanks!! :-) Please make sure that you don't forget the drop shadow below the whole icon.

**Comment by patcon** [comment]
Not sure how you feel about using svg as src, but that would allow the canonical file to exist nicely in version-control so design contributions don't have to filter back through PSD's outside the repo :)
