### ISSUE TITLE
Alphanumeric passcodes

### ISSUE THREAD

**Issue by jffrymrtn** [jffrymrtn/writeily-pro#49]

**Comment by jffrymrtn** [comment]
This seems simple enough (store a string instead of a four digit int in Shared Preferences). Going to see if this can be done in 1.3. If not, will move to 1.4

**Comment by jffrymrtn** [comment]
Might be bigger than I'm assuming, since it'll also need a dynamic Lock screen (eg. if alphanumeric, show one EditText, but if 4-digit pin show the four EditText we have now)

**Comment by plafue** [comment]
Before i could implement this, i need to know if we give the user the choice between an alphanumeric passcode and a "PIN". As you mention, it could be a slightly bigger task if we want to differentiate between the both in the future.

I think I could easily get it done for 1.3.

**Comment by jffrymrtn** [comment]
Yes, in the settings they can tap "Pin Lock" or "Alphanumeric Lock", and if one is toggled on, the other switches off.
