### ISSUE TITLE
Fix actionMode duplicating bar over App bar when a note is selected

### ISSUE THREAD

**Issue by jffrymrtn** [jffrymrtn/writeily-pro#5]

**Comment by jffrymrtn** [comment]
Seems to be caused by a few Holo styles.
 fitsSystemWindows seems to have been interfering. Removing it helped, but still the same issue.

**Comment by jffrymrtn** [comment]
Been trying to figure this out since forever. Anyone know what the issue might be? Has to be something in the themes.xml...

**Comment by plafue** [comment]
:)

**Comment by jffrymrtn** [comment]
@plafue WOW. That was seriously the fix??? O_O

**Comment by jffrymrtn** [comment]
That makes sooo much sense I knew it was something silly like this AHHHHHHHHH

I feel so dumb now haha. Nice nice nice nice nice job :+1: :+1: :+1: :+1:

**Comment by plafue** [comment]
Hehehehe, you are very welcome :) More to come! I cannot sleep and i think i can get a couple more things before i go to work :P :dancer:
