### ISSUE TITLE
Link between notes ...

### ISSUE THREAD

**Issue by davydsantos** [jffrymrtn/writeily-pro#50]
I'm trying to create a link between 2 notes in the app and it's not working. I don't know if it's a bug or Im doing something wrong. The file contents are:
```
file name: file1  
file contents: * [test](file2)  
file name: file2  
file contents: asdf  
```
After clicking on the link I see only a blank page.

**Comment by jffrymrtn** [comment]
This is because links expect an http URL. I'll see what I can do about local URLs (though no guarantees since I'm using a third-party library for the Markdown parser).

**Comment by davydsantos** [comment]
I created a fix for this issue but don't know how to send it to you for evaluation.

**Comment by jffrymrtn** [comment]
Nice! You can create a Pull Request if you forked the original repository, and I can review it here.

https://github.com/jffrymrtn/writeily-pro/pulls

**Comment by davydsantos** [comment]
Merged into current master branch
