### ISSUE TITLE
Toolbar in About Screen

### ISSUE THREAD

**Issue by jffrymrtn** [jffrymrtn/writeily-pro#62]
After quick researching and much thinking, it seems this is a "bug" (?) or shortcoming by Google on AppCompat v21...

http://stackoverflow.com/questions/26509180/no-actionbar-in-preferenceactivity-after-upgrade-to-support-library-v21

http://stackoverflow.com/questions/26564400/creating-a-preference-screen-with-support-v21-toolbar

Tagging @Minty123 

-----

Although StackOverflow shows some people have got it to show by hacking through code, I'm not sure it's worth it. From past experience some device manufacturers might change something in their OS that something hacky like this might cause a crash in (this actually currently happens on Writeily Pro on some Samsung Galaxy devices, and I had to mark those devices as incompatible on the Play Store).

Since it's a relatively minor issue, I may just let it go until it heightens to become a big issue for users... I'd rather not hack through it if it's something Google might fix eventually. Thoughts?

**Comment by Minty123** [comment]
Hey there!

I thought of something that should be a pretty stable workaround for this problem. See #64

**Comment by jffrymrtn** [comment]
Works thanks to @Minty123 . Incredible work !
