### ISSUE TITLE
block showed in the top-left corner when shortcuts bar disabled

### ISSUE THREAD

**Issue by iptux** [jffrymrtn/writeily-pro#72]
see [screen shot](http://postimg.org/image/3oqtiisdh/)

Light theme will show a white block

**Comment by jffrymrtn** [comment]
Interesting. Not seeing this on my device (Nexus 4 on 5.0.1). What device and version are you running?

**Comment by iptux** [comment]
Note 3 on CM11(4.4.4)

**Comment by iptux** [comment]
Use `LinearLayout` in note editing layout may fix this
