### ISSUE TITLE
Do not overwrite previously imported files

### ISSUE THREAD

**Issue by jffrymrtn** [jffrymrtn/writeily-pro#78]

**Comment by plafue** [comment]
Is this still relevant? What do we mean by that? Accidentally overwriting of files during the import process?
What should be the expected behaviour if there is a name collision? Adding a suffix? Just reporting the collisions?

**Comment by jffrymrtn** [comment]
If the user imports a file with the same filename, the import will overwrite the older one that was there.

Not a big deal, though.

**Comment by plafue** [comment]
So what is the expected then?

**Comment by jffrymrtn** [comment]
I think the best course of action is to show a dialog asking if they want to overwrite the file

**Comment by plafue** [comment]
Ok, so if the user does not provide a name don't we skip it, right?

**Comment by jffrymrtn** [comment]
Yep! if they don't want to overwrite, just don't import the file
